import type { IArmyData } from '@/classes/Army'
import { armyTraits, scaleBonus, startingMorale } from '@/classes/Army'
import { CoreContent } from './ContentLoader'
import { sanitizeFilename } from './CharacterTransfer'
import { downloadText } from './ArmyTransfer'

/**
 * A plain-text summary of an army and its current battle state, in the same format as the
 * character statblock (see StatblockExport.ts) so the two paste side by side.
 */

const SECTION_RULE = '-'.repeat(60)
const TITLE_RULE = '='.repeat(60)

function line(label: string, value: string, indent = '    '): string {
  return `${indent}${label}: ${value}`
}

export function generateArmyStatblockText(army: IArmyData): string {
  const { divisions, stratagems, talents, rules } = CoreContent.armies
  const bonus = scaleBonus(army)
  const maxMorale = startingMorale(army, rules)
  const deployed = army.divisions.filter((d) => d.deployed).length

  const out: string[] = []
  out.push(TITLE_RULE)
  out.push(army.name || 'Unnamed Army')
  out.push(`Scale ${army.scale} | Party Level ${army.partyLevel}`)
  out.push(TITLE_RULE)
  out.push('')

  out.push('TRAITS')
  // Division Traits on one line, the Defining Feature on its own below
  const traits = armyTraits(army, divisions).filter((t) => t !== army.definingFeature)
  out.push(`  ${traits.length ? traits.join(', ') : 'None'}`)
  if (army.definingFeature) out.push(`  Defining Feature: ${army.definingFeature}`)
  out.push('')

  out.push('BATTLE')
  out.push(`  Deployed: ${deployed} / ${army.scale}`)
  out.push(`  Scale Bonus: ${bonus ? `+${bonus} Morale, +${bonus}[CD] on attacks against divisions` : 'None'}`)
  const broken = army.divisions.filter((d) => d.broken).length
  if (broken) out.push(`  Broken Divisions: ${broken}`)
  out.push('')

  out.push(SECTION_RULE)
  out.push(`DIVISIONS (${army.divisions.length} / ${army.scale})`)
  if (!army.divisions.length) out.push('  None')
  for (const d of army.divisions) {
    const div = divisions.find((x) => x.id === d.divisionId)
    if (!div) continue
    const name = d.nickname ? `${d.nickname} (${div.name})` : div.name
    const status = [d.broken ? 'BROKEN' : '', d.deployed ? '' : 'Not deployed'].filter(Boolean).join(', ')
    out.push('')
    out.push(`  - ${name} [${div.types.join(', ')}]${status ? ` - ${status}` : ''}`)
    out.push(line('Morale', `${d.morale} / ${maxMorale}`))
    out.push(line('Resistance', `${div.resistance}`))
    const bonusCD = d.deployed ? bonus : 0
    const effects = div.attack.effects?.length ? ` ${div.attack.effects.join(', ')}` : ''
    out.push(
      line(
        div.attack.ranged ? 'Ranged Attack' : 'Attack',
        `${div.attack.damageCD + bonusCD}[CD]${effects}${bonusCD ? ` (Base ${div.attack.damageCD} + Scale ${bonusCD})` : ''}`,
      ),
    )
    out.push(line('Buff', div.buff ? `${div.buff.name}${d.broken ? ' (inactive - Broken)' : ''}` : 'None'))
    const strat = stratagems.find((s) => s.id === d.stratagemId)
    if (strat) {
      const uses = strat.usesPerScene ? ` - Uses: ${strat.usesPerScene - d.stratagemUsesSpent} / ${strat.usesPerScene} left` : ''
      out.push(line('Stratagem', `${strat.name} (${strat.kind === 'order' ? 'Order' : 'Passive'})${uses}`))
    }
    const flags = [d.freeMoveUsed ? 'Free Move used' : 'Free Move available']
    if (d.stratagemId === 'mounted_infantry') flags.push(d.mounted ? 'Mounted' : 'Dismounted')
    out.push(line('Status', flags.join(', ')))
  }
  out.push('')

  out.push(SECTION_RULE)
  out.push('ARMY TALENTS')
  const held = talents.filter((t) => army.talentIds.includes(t.id))
  if (!held.length) out.push('  None')
  for (const t of held) out.push(`  - ${t.name}`)
  out.push('')

  out.push(TITLE_RULE)
  out.push('Generated by Ascension Web - heroclub.app/ascension-web')
  out.push(TITLE_RULE)
  return out.join('\n')
}

export function downloadArmyStatblock(army: IArmyData): void {
  downloadText(generateArmyStatblockText(army), `${sanitizeFilename(army.name)}-statblock.txt`)
}
